# LA MIGRAZIONE DEI SAPERI E L'ARTE OROLOGIAIA

Uno sguardo sulla storia dell'orologeria in Europa evidenzia che l’arte orologiaia si diffonde con l'emigrazione delle persone esperte in tale campo. I grossi centri orologiai di Ginevra e di Londra ed i piccoli centri del Jura svizzero francese si sviluppano dopo l'arrivo degli ugonotti, maestri-orologiai espulsi dalla Francia nel 1680.@cipolla1972diffusion @hilaire1997transferts

Il distretto orologiao di Karlstein nasce con l’arrivo di un artigiano esperto. 
In Friuli, nel 1700, i fabbri di Pontebba, alla chiusura dell'attività di produzione di archibugi, si spostano in Carnia e in Ungheria. Sono presenti a Comeglians ed Ampezzo, ma anche in Ungheria a Nagykanizsa. Leonardo Nascimbeni (1735- 1758),fabbro, e Domenico Nascimbeni (1728-1768) orologiaio. (documento)

Nel 1685, l'orologiaio Lorenzo Zearo di Moggio svolge l’attività di moderatore dell’orologio da torre di Udine. L’orologiaio Giovanni Pesamosca di Chiusaforte apporta, nel 1734, alcune migliorie meccaniche all’orologio da torre di Piazza della Libertà di Udine. (documento)
L'orologiaio Claudio Zearo di Moggio, nel 1744, assume l'incarico di moderatore per l’orologio da torre del Municipio di Pordenone. 

In Carnia, la vocazione orologiaia è promossa dalle attività commerciali dei Cramars che interpretano la domanda che proviene dal mercato dei territori situati lungo le vie commerciali fluviali ed i centri delle grandi Fiere di Augusta, Francoforte,Lipsia. L’attività dei Cramars si sviluppa nel nord della Carnia, a partire dal XV secolo e con maggior intensità dal XVIII e si svolge nei paesi dellíimpero Asburgico e dell'Istria. Essi, al ritorno dai loro viaggi, portano con sè gli attrezzi per la lavorazione del ferro richiesti dai fabbri di fino e dal falegname e, come novità, un orologio domestico costruito in legno proveniente dalla Boemia. L’ orologio domestico Boemo viene riprodotto in legno nella Foresta Nera a Schonach e a Karlstein in Austria , ed in ferro forgiato a Morez e a Pesariis . Morbier, Matrei e Pesariis producono orologi da torre in ferro battuto. 
L'inizio di questí attività avviene nel 1560 a Matrei con Forstlechner, nel 1660 a Morbier con i fratelli Mayet, nel 1660 a Pesariis con Cristoforo Capellari . (documento)

A Pesariis, possiamo supporre che il primo artigiano orologiaio abbia svolto l’apprendistato in uno dei paesi situati sulla via commerciale che unisce Pesariis a san Candido con Lienz e Matrei frequentata dai Cramars carnici. Matrei è un antico centro siderurgico dove si è sviluppata l’arte della fusione e della lavorazione del ferro e la produzione di orologi da torre . Il mestiere di orologiaio si apprende nei centri di formazione dei maestri-orologiaio sorti a Vienna-Innsbruck-Graz e Friedberg. L'apprendistato, della durata di cinque anni, si svolge presso un maestro-orologiaio e, per conseguire il titolo di maestro-orologiaio, si aggiungono altri tre anni di attività svolti all’estero. 


