--- 
title: "LA TRADIZIONE PLURISECOLARE 
DEGLI OROLOGIAI DI PESARIIS"
author: "a cura di Alceo Solari^[Alceo Solari nasce a Pesariis nel 1941. Figlio di Alfeo Solari fa parte della VII ed ultima generazione degli orologiai Solari di Pesariis. Si diploma al Malignani di Udine, specializzandosi poi in Germania e Svizzera. Diventa direttore tecnico della Fratelli Solari S.p.a. dal 1964 al 1972. Dal 1972 al 1980 è direttore commerciale dell'Azienda. Riorganizza la rete commerciale in Italia fondando ditte distributrici e fornitrici di servizi di assistenza tecnica per la linea di orologeria industriale. Durante la sua direzione i volumi di vendita crescono di ben otto volte, con un' espansione in diversi paesi europei. Fino al 1976 è componente del Consiglo di Amministrazione e consigliere delegato dal 1973 al 1976.] <br> dell'ultima generazione degli orologiai Solari"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
---


# Prefazione {-}


Perchè in un piccolo paese di montagna del Friuli nasce un'attività orologiaia che si sviluppa poi in industria e che prosegue, di generazione in generazione, per quasi tre secoli? 

Quali sono i fattori che permettono tutto questo? Perchè il marchio f.lli Solari diventa un marchio conosciuto in tutto il mondo e tuttora attrattivo per il mercato dei teleindicatori delle stazioni ferroviarie e degli aereoporti? 

Sono questi i quesiti di un protagonista della storia dell' orologeria pesarina, che da pensionato inizia la sua instancabile attività di ricerca per tentare di documentare e raccontare una storia non ancora scritta anche causa la mancanza di fonti documentative, archivio andato perso durante la seconda Guerra mondiale. 

Una storia ricostruita attraverso un paziente e lungo viaggio documentativo lungo I paesi alpini dell'Europa, dove scritti in lingue diverse, dal francese, all’inglese al tedesco parlano di orologi da torre e domestici inventati e costruiti in villaggi di montagna, a partire dal 1600. Attraverso il metodo comparativo Alceo riesce a suffragare una storia che per 250 anni si sviluppa a Pesariis, dove tutt'ora opera una sede distaccata della ditta Solari di Udine. 

La sua tesi si basa su tre enunciati che verranno poi ampiamente sviluppati e documentati nel testo: 

* la storia dell’orologeria pesarina può essere ricostruita a partire da uno sguardo rivolto alla storia dell’orologeria pubblica delle valli alpine d’Europa, a partire dal 1600; 

* nel 1700 la valle è stata coinvolta da migrazioni di saperi e di persone verso le Alpi e l’Adriatico; 

* legami sociali di paese hanno contribuito alla storia della ditta Solari, che dalla fase artigianale si è sviluppata in industria, andando a costituire una delle più importanti fonti di lavoro per l’intera valle dal dopoguerra agli anni ’90; 

* il genio inventore di Remigio e abili commercianti hanno dato origine al marchio Solari, tutt’ora valido sul mercato mondiale. 


